name: Build and Test

on:
  push:
    branches:
      - main
      - tdd
  pull_request:
    branches:
      - main
      - tdd

jobs:
  checkstyle:
    name: Lint with Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Lint
        run: mvn checkstyle:check

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Tests
        run: mvn test